### ISSUE TITLE
Plugin should warn about lower case letters in enums and records

### ISSUE THREAD

**Issue by sasq64** [cross-language-cpp/djinni-intellij-plugin#18]
Even though mixed case is allowed in enums and records, they are converted to upper case in the generated Java code, so it is not a good idea to use it.

(Maybe this should be fixed in Djinni proper instead).

**Comment by a4z** [comment]
I think I would prefer to not convert this to uppercase in the generated code.

IMHO it is basically wrong doing so, maybe this was a coding convention of Dropbox, but for general use, if a user names something FoO the generated entity should also be called FoO .

**Comment by jothepro** [comment]
I agree that it may be better to adjust djinni instead of adding warnings to the plugin.

Personally I intend to keep the plugin as simple as possible, not adding fancy features beyond a somewhat correct parser, basic syntax highlighting and type suggestions. Simply because I think my time is invested better in improving the actual djinni generator!

If you have good ideas on how to improve the plugin don't hesitate to contribute! :)
